config/routes.rb
Rails.application.routes.draw do

  resources :clients
  resources :cars
  resources :rents
  root 'cars#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :rents
  has_many :clients, through: :rents

  validates :car_brand, presence: true,
                        length: { in: 3..30 }
  validates :car_model, presence: true,
                        length: { in: 1..30 }
  validates :fuel_type, presence: true,
                        length: { in: 1..30 }
  validates :num_of_seats,  presence: true,
                            numericality: { greater_than_or_equal_to: 2, less_than_or_equal_to: 7 }
  validates :price_per_day, presence: true

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :rents

  has_many :cars, through: :rents
  validates :first_name,   presence: true, length: { minimum: 3, maximum: 50 }
  validates :last_name,    presence: true, length: { minimum: 3, maximum: 50 }
  validates :email,        format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :telephone,    presence: true, length: { minimum: 3, maximum: 140 }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/rent.rb
class Rent < ActiveRecord::Base
  belongs_to :client
  belongs_to :car
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to root_path
      flash[:success] = "Dodano nowy samochód"
    else
      flash[:warning] = "Coś poszło nie tak"
      render :new
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    if @car.update_attributes(car_params)
      flash[:success] = "Edycja zakończona powodzeniem."
      redirect_to car_path(@car)
    else
      flash.now[:error] = "Coś poszło nie tak. Spróbuj ponownie."
      render :edit
    end
  end

  def show 
    @car = Car.find(params[:id])
    @rent = Rent.new(car_id: @car.id)
  end

  def destroy
    Car.find(params[:id]).destroy
    flash[:notice] = "Samochód został usunięty"
    redirect_to cars_path
  end

  private

  def car_params
    params[:car].permit(:car_brand, :car_model, :fuel_type, :num_of_seats, :price_per_day)
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      flash[:notice] = "Added client."
      redirect_to clients_path
    else
      flash[:notice] = "Unable to add client."
      render :new
    end
  end

  def edit
   @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
      if @client.update_attributes(client_params)
        # redirect_to(:action => 'show', :id => @client.id) 
        # flash[:notice] = "Client updated."
          redirect_to clients_path
      else
        render :edit
      end
  end

  def destroy
    Client.find(params[:id]).destroy
    flash[:notice] = "Removed client."
    redirect_to clients_path
  end

  private
  def client_params
    params[:client].permit(:first_name, :last_name, :email, :telephone)
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController

  def index
    @rents = Rent.all
  end

  def create
    @rent = Rent.new(rent_params)
    if @rent.save
      flash[:notice] = "Samochód wypożyczony"
      redirect_to root_path
      RentMailer.car_is_waiting(@rent).deliver!
    else
      flash[:notice] = "Nie można wypożyczyć tego samochódu"
      redirect_to root_path
    end
  end

  private

  def rent_params
    params[:rent].permit(:car_id, :client_id, :rent_from_date, :number_of_days_rent)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/cars/edit.html.erb
<div class="row">
	<h1>Edycja nowego samochodu</h1>
</div>
<%= link_to 'Powrót', cars_path %>
<div class="row">
	<section class="form">
		<%= simple_form_for @car do |f| %>
		  <div class="form-group"><%= f.input :car_brand, placeholder: 'Marka samochodu' %></div>
		  <div class="form-group"><%= f.input :car_model, placeholder: 'Model samochodu' %></div>
		  <div class="form-group"><%= f.input :fuel_type, placeholder: 'Rodzaj paliwa' %></div>
		  <div class="form-group"><%= f.input :num_of_seats, placeholder: 'Liczba miejsc' %></div>
		  <div class="form-group"><%= f.input :price_per_day, placeholder: 'Cena za dzień' %></div>
		  <div class="form-group"><%= f.button :submit, 'Zapisz' %></div>
		<% end %>
	</section>
</div>

app/views/cars/index.html.erb
<div class="row">
	<h1>Lista wszystkich samochodów</h1>
</div>
<div class="row">
	<%= link_to "Dodaj samochód", new_car_path %>
</div>
<div class="row">
	<table class="table table-striped">
		<tr>
			<th>Marka</th>
			<th>Model</th>
			<th>Rodzaj paliwa</th>
			<th>Liczba miejsc</th>
			<th>Cena za dzień</th>
			<th>Akcje</th>
		</tr>
		<% @cars.each do |car| %>
			<tr>
				<td><%= car.car_brand %></td>
				<td><%= car.car_model %></td>
				<td><%= car.fuel_type %></td>
				<td><%= car.num_of_seats %></td>
				<td><%= number_to_currency(car.price_per_day, unit: 'PLN') %></td>
				<td>
					<div class="btn-group btn-group-xs" role="group"> 
						<%= link_to 'Usuń', car_path(car), method: :delete, data: {confirm: "Jesteś pewny?!"}, class: "btn btn-danger" %>
						<%= link_to 'Edytuj', edit_car_path(car), class: "btn btn-warning" %>
						<%= link_to 'Wynajmij', car_path(car), class: "btn btn-info" %>
					</div>
				</td>
			</tr>
		<% end %>
	</table>
</div>

app/views/cars/new.html.erb
<div class="row">
	<h1>Dodawanie nowego samochodu</h1>
</div>
<div class="row">
	<div class="col-md-6">
		<section class="form">
			<%= simple_form_for @car do |f| %>
			  <%= f.input :car_brand, placeholder: 'Marka samochodu', label: false %>
			  <%= f.input :car_model, placeholder: 'Model samochodu', label: false %>
			  <%= f.input :fuel_type, placeholder: 'Rodzaj paliwa', label: false %>
			  <%= f.input :num_of_seats, placeholder: 'Liczba miejsc', label: false, as: :integer %>
			  <%= f.input :price_per_day, placeholder: 'Cena za dzień', label: false %>
			  <%= f.button :submit, 'Zapisz' %></div>
			<% end %>
		</section>
	</div>
</div>

app/views/cars/show.html.erb
<div class="row">
	<h1>Wypożycz ten samochód</h1>
	<h2><%= @car.car_brand %> <%= @car.car_model %></h2>
</div>
<%= link_to 'Powrót', cars_path %>
<div class="row">
	<div class="col-md-6">
		<section class="form">
			<%= simple_form_for @rent do |f| %>
			  <%= f.input :car_id, as: :hidden %>
			  <%= f.input :client_id, collection: Client.all, label_method: :full_name, placeholder: 'Klient', label: false %>
			  <%# f.input :rent_from_date, as: :string, label: 'Data rozpoczęcia' %>
			  <div class="form-group">
			  	<div class="row">
				  	<div class="col-md-4"><label class="string optional control-label" for="rent_rent_from_date">Data rozpoczęcia</label></div>
				  	<div class="col-md-8"><input type="date" class="form-control" name="rent[rent_from_date]" value="<%= @rent.rent_from_date %>"></div>
				  </div>
				  
				</div>
			  <%= f.input :number_of_days_rent, label: false, collection: 2..7, default: '-' %>
			  <%= f.button :submit, 'Zapisz' %>
			<% end %>
		</section>
	</div>
</div>

app/views/clients/edit.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="row">
			<h4><span class="text-success"><i class="fa fa-bug"></i></span> Edycja Klienta: 
				<%= @client.first_name%><%= @client.last_name %></h4>
			<p><%= link_to 'Wróć do listy klientów', clients_path %></p>
			<hr>
		</div>
		<div class="row">
				<%= simple_form_for(@client) do |form| %>
					<%= form.input :first_name %>
					<%= form.input :last_name %>
					<%= form.input :email %>
					<%= form.input :telephone %>
					<%= form.submit %>
				<% end %>
		</div>
	</div>
</div>

app/views/clients/index.html.erb
<div class="row">
  <h1>Lista wszystkich klientów</h1>
</div>
<div class="row">
  <%= link_to "Dodaj klienta", new_client_path %>
</div>
<div class="row">
  <table class="table table-striped">
    <tr>
      <th>Imię</th>
      <th>Nazwisko</th>
      <th>E-mail</th>
      <th>Telefon</th>
      <th>Akcje</th>
    </tr>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.email %></td>
        <td><%= client.telephone %></td>
        <td>
          <div class="btn-group btn-group-xs" role="group"> 
            <%= link_to 'Edytuj', edit_client_path(client), class: "btn btn-info" %>
            <%= link_to 'Usuń', client_path(client), method: :delete, data: {confirm: "Czy jesteś pewien, że chcesz usunąć klienta#{client.first_name} #{client.last_name}?"}, class: "btn btn-danger" %>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/clients/new.html.erb
<div class="row">
	<h1>Dodaj nowego klienta</h1>
</div>
<div class="row">
	<div class="col-md-6">
		<section class="form">
			<%= simple_form_for @client do |f| %>
				<%= f.input :first_name, placeholder: 'Imię', label: false %>
				<%= f.input :last_name, placeholder: 'Nazwisko', label: false %>
				<%= f.input :email, placeholder: 'E-mail', label: false %>
				<%= f.input :telephone, placeholder: 'Nr telefonu, np 901901901', label: false %>
				<%= f.button :submit, 'Dodaj' %>
			<% end %>
		</section>
	</div>
</div>

app/views/clients/show.html.erb
<h4>Client profile</h4>

<p>First name: <%= @client.first_name %></p>
<p>First name: <%= @client.last_name %></p>
<p>E-mail: <%= @client.email %></p>
<p>Telephone: <%= @client.telephone %></p>


<p><%= link_to 'client list', clients_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RentACar</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name + '_' + action_name %>">
	<div class="container">
		<div class="col-md-10 col-md-offset-1">
			<div class="row"><%= flash_messages %></div>
			<%= yield %>
		</div>
	</div>
</body>
</html>

app/views/rents/index.html.erb
<div class="row">
	<h1>Lista wszystkich wypożyczeń</h1>
</div>
<div class="row">
	<%# link_to "Dodaj samochód", new_car_path %>
</div>
<div class="row">
	<table class="table table-striped">
		<tr>
			<th>Marka</th>
			<th>Model</th>
			<th>Rodzaj paliwa</th>
			<th>Liczba miejsc</th>
			<th>Cena za dzień</th>
			<th>Akcje</th>
		</tr>
		<% @rents.each do |rent| %>
			<tr>
			<%= rent.car_id %>	
			</tr>
		<% end %>
	</table>
</div>